import csv
import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

from .config import DatasetConfig
from .manifest import DATASET_MANIFEST_FILENAME, write_dataset_manifest

MetadataRow = dict[str, object]

METADATA_SCHEMA_VERSION = "2.1"


def class_mapping(classes: tuple[str, ...]) -> dict[str, int]:
    return {class_name: index for index, class_name in enumerate(classes)}


def config_to_dict(config: DatasetConfig) -> dict[str, Any]:
    data = asdict(config)
    data["output_dir"] = str(config.output_dir)
    data["classes"] = list(config.classes)
    return data


def write_metadata(output_dir: Path, rows: list[MetadataRow]) -> None:
    if not rows:
        return

    metadata_path = output_dir / "metadata.csv"
    fieldnames = [
        "filename",
        "mask_filename",
        "metadata_schema_version",
        "application_version",
        "python_version",
        "numpy_version",
        "pillow_version",
        "subset",
        "class",
        "class_id",
        "image_size",
        "shape_type",
        "seed",
        "status",
        "background",
        "foreground",
        "line_width",
        "scale",
        "rotation_degrees",
        "center_x",
        "center_y",
        "radius",
        "shape_width",
        "shape_height",
        "shape_area",
        "bbox_left",
        "bbox_top",
        "bbox_right",
        "bbox_bottom",
        "color_mode",
        "fill_mode",
        "noise_level",
        "margin",
        "edge_clipping",
        "min_visible_ratio",
        "clipping_side",
    ]

    with metadata_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_class_mapping(output_dir: Path, classes: tuple[str, ...]) -> None:
    mapping_path = output_dir / "class_mapping.json"
    with mapping_path.open("w", encoding="utf-8") as file:
        json.dump(class_mapping(classes), file, indent=2)
        file.write("\n")


def write_generation_config(output_dir: Path, config: DatasetConfig) -> None:
    config_path = output_dir / "generation_config.json"
    with config_path.open("w", encoding="utf-8") as file:
        json.dump(config_to_dict(config), file, indent=2)
        file.write("\n")


def write_generation_log(output_dir: Path, config: DatasetConfig, total_images: int) -> None:
    log_path = output_dir / "log.txt"
    lines = [
        "ShapeDomainLab generation log",
        f"Output directory: {output_dir}",
        f"Image size: {config.image_size}",
        f"Classes: {', '.join(config.classes)}",
        f"Train count per class: {config.train_count}",
        f"Validation count per class: {config.val_count}",
        f"Test count per class: {config.test_count}",
        f"File format: {config.file_format}",
        f"Save masks: {config.save_masks}",
        f"Color mode: {config.render.color_mode}",
        f"Background color: {config.render.background_color}",
        f"Foreground color: {config.render.foreground_color}",
        f"Fill mode: {config.render.fill_mode}",
        f"Rotation range: {config.render.rotation_range[0]} to {config.render.rotation_range[1]} degrees",
        f"Scale range: {config.render.scale_range[0]} to {config.render.scale_range[1]}",
        f"Center offset range: {config.render.center_offset_range[0]} to {config.render.center_offset_range[1]} pixels",
        f"Edge clipping: {config.render.edge_clipping}",
        f"Minimum visible ratio: {config.render.min_visible_ratio}",
        f"Background noise level: {config.render.noise_level}",
        f"Random seed: {config.seed}",
        f"Total images: {total_images}",
        "Subsets: train, val, test",
        "Status: completed",
        "",
    ]
    log_path.write_text("\n".join(lines), encoding="utf-8")


def write_dataset_readme(output_dir: Path, config: DatasetConfig, total_images: int) -> None:
    readme_path = output_dir / "README.md"
    class_list = "\n".join(f"- `{class_name}`" for class_name in config.classes)
    text = f"""# ShapeDomainLab Dataset

This dataset was generated by ShapeDomainLab.

## Structure

```text
dataset/
  train/
  val/
  test/
  masks/  (optional)
  metadata.csv
  class_mapping.json
  generation_config.json
  dataset_manifest.json
  log.txt
  quality_report.json  (after quality validation)
  quality_report.md    (after quality validation)
  README.md
```

The dataset contains independent `train`, `val`, and `test` subsets.

## Classes

{class_list}

## Counts

- Train images per class: {config.train_count}
- Validation images per class: {config.val_count}
- Test images per class: {config.test_count}
- Total images: {total_images}

## Image Parameters

- Image size: {config.image_size} x {config.image_size}
- File format: {config.file_format}
- Color mode: {config.render.color_mode}
- Background color: {config.render.background_color}
- Foreground color: {config.render.foreground_color}
- Fill mode: {config.render.fill_mode}
- Rotation range: {config.render.rotation_range[0]} to {config.render.rotation_range[1]} degrees
- Scale range: {config.render.scale_range[0]} to {config.render.scale_range[1]}
- Center offset range: {config.render.center_offset_range[0]} to {config.render.center_offset_range[1]} pixels
- Edge clipping: {config.render.edge_clipping}
- Minimum visible ratio: {config.render.min_visible_ratio}
- Background noise level: {config.render.noise_level}
- Save binary masks: {config.save_masks}
- Random seed: {config.seed}

## Metadata schema

`metadata.csv` uses schema version {METADATA_SCHEMA_VERSION}. Every row contains the image label, independent sample seed, sampled rendering values, nominal geometry, image-coordinate bounds, clipping information, and the application and library versions used for generation.

`generation_config.json` uses configuration schema version `{config.config_version}`. The version allows future readers to distinguish configuration formats while preserving compatibility with earlier files that omit this field.

`shape_width`, `shape_height`, and `shape_area` describe the generated geometric primitive before rasterization. `bbox_left`, `bbox_top`, `bbox_right`, and `bbox_bottom` are the bounds after rotation and placement; they can extend beyond the image frame when edge clipping is enabled.

When binary masks are enabled, `masks/<subset>/<class>/` contains one PNG `L`-mode mask per generated image. A mask uses `0` for background and `255` for the rendered shape; its relative path is stored in `mask_filename`.

## Quality reports

After validation, `quality_report.json` and `quality_report.md` contain structural checks, duplicate screening, geometry summaries, and mask foreground-area summaries when masks are enabled. Exact duplicates across `train`, `val`, and `test` are reported as errors; average-hash near-duplicates are warnings for review.

## Service Files

- `metadata.csv`: per-image labels, optional mask paths, provenance, rendering parameters, geometry, and bounds.
- `class_mapping.json`: mapping between class names and numeric class IDs.
- `generation_config.json`: configuration used to generate this dataset.
- `{DATASET_MANIFEST_FILENAME}`: SHA-256 hashes and byte sizes for generated dataset artifacts.
- `log.txt`: short generation summary.
- `quality_report.json` and `quality_report.md`: machine-readable and human-readable results of the post-generation quality validation.

## PyTorch Usage

The `train/`, `val/`, and `test/` directories are compatible with `torchvision.datasets.ImageFolder`.
"""
    readme_path.write_text(text, encoding="utf-8")


def write_dataset_service_files(
    output_dir: Path,
    config: DatasetConfig,
    rows: list[MetadataRow],
) -> None:
    total_images = len(rows)
    write_metadata(output_dir, rows)
    write_class_mapping(output_dir, config.classes)
    write_generation_config(output_dir, config)
    write_generation_log(output_dir, config, total_images)
    write_dataset_readme(output_dir, config, total_images)
    write_dataset_manifest(output_dir)
